In [21]:
import pandas as pd
import numpy as np

In [22]:
data = pd.read_csv('Precip_pdx.csv')
data.head(30)

,YR,MO,1,2,3,4,5,6,7,8,...,21,22,23,24,25,26,27,28,29,30
0,1940,6,M,M,M,M,M,M,M,M,...,M,M,M,M,M,M,M,M,M,M
1,1941,6,2,0,0,0,16,3,5,T,...,T,T,0,4,9,0,0,T,0,0
2,1942,6,0,T,0,0,46,4,T,14,...,0,0,0,24,17,T,0,0,0,0
3,1943,6,23,33,0,6,0,0,0,0,...,44,11,1,0,0,0,0,0,0,0
4,1944,6,25,T,T,0,0,0,T,T,...,0,0,0,0,1,T,0,0,0,T
5,1945,6,0,0,T,0,0,1,0,T,...,T,0,0,0,0,0,0,T,T,0
6,1946,6,0,T,T,0,26,3,24,T,...,T,6,5,13,5,15,1,50,5,2
7,1947,6,44,23,14,4,3,11,45,21,...,0,0,0,0,1,11,16,T,0,0
8,1948,6,0,0,0,T,0,0,0,0,...,T,T,0,T,0,T,0,0,0,0
9,1949,6,T,0,0,0,0,0,0,T,...,0,0,0,1,1,9,0,18,1,0
10,1950,6,0,0,0,0,T,T,41,0,...,0,T,37,19,T,T,0,0,0,0
11,1951,6,0,0,0,1,T,1,0,0,...,0,0,0,0,0,0,0,0,0,0
12,1952,6,0,0,0,0,T,T,0,0,...,20,0,T,1,0,0,17,39,27,T
13,1953,6,T,T,3,0,34,55,15,1,...,0,0,1,0,0,1,1,13,4,0
14,1954,6,0,0,11,38,14,10,T,57,...,0,0,0,0,2,6,14,0,0,81
15,1955,6,T,8,20,8,0,0,0,0,...,0,15,7,10,3,5,37,63,5,1
16,1956,6,T,T,20,19,9,3,T,T,...,0,0,0,0,0,0,0,0,0,0
17,1957,6,0,0,0,0,5,0,T,0,...,T,0,0,0,0,1,0,0,0,0
18,1958,6,0,1,T,0,12,170,0,T,...,0,0,0,70,0,T,T,2,34,2
19,1959,6,0,T,4,52,10,4,T,24,...,0,0,T,T,T,T,30,22,0,0
20,1960,6,0,0,0,0,0,0,0,0,...,0,0,0,0,T,0,0,0,0,0
21,1961,6,0,0,0,0,0,28,0,T,...,0,0,0,0,0,T,T,0,2,0
22,1962,6,0,46,22,T,T,0,0,T,...,0,0,0,0,1,T,0,0,0,0
23,1963,6,0,10,0,30,10,0,2,T,...,20,18,T,42,4,0,8,8,7,1
24,1964,6,3,0,3,40,4,38,19,7,...,0,0,0,0,0,T,8,0,0,0
25,1965,6,0,0,0,0,0,0,0,T,...,0,0,0,0,0,0,0,0,0,0
26,1966,6,0,T,T,0,0,T,2,0,...,3,22,17,0,0,0,8,40,0,0
27,1967,6,1,0,0,0,0,0,0,0,...,44,40,0,0,0,T,0,0,0,0
28,1968,6,97,7,0,0,0,0,T,0,...,29,24,0,0,0,0,1,23,1,0
29,1969,6,0,0,0,0,6,2,0,0,...,NaN,33,87,22,29,58,28,32,0,0

In [30]:
days = []
total = 0
no_rain = 0
rain = []
for value in data["22"]:
    if value[0].isdigit():
        total += 1
        days.append(value)
        if value[0] == "0":
            no_rain += 1
        else:
            rain.append(int(value))
avg_rain = np.mean(rain)
            
print("Total period of record is {} years".format(total))
print ("{}% chance of not raining on 6/22".format(((no_rain/total)*100)))
print ("Average rainfall when it did rain was {} mm".format(avg_rain))

Total period of record is 60 years
70.0% chance of not raining on 6/22
Average rainfall when it did rain was 16.666666666666668 mm